# Generated by Django 3.2.2 on 2021-05-07 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlsId', models.CharField(default='', max_length=20)),
                ('price', models.CharField(default='', max_length=20)),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('isActive', models.BooleanField(default=False)),
                ('thumbnail', models.CharField(blank=True, max_length=100, null=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyInfo',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapi_app.property')),
                ('propertyId', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
                ('history', models.TextField(blank=True, null=True)),
                ('fullAddress', models.TextField(blank=True, null=True)),
                ('yearBuilt', models.CharField(blank=True, max_length=10)),
            ],
            bases=('webapi_app.property',),
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.DecimalField(blank=True, decimal_places=10, max_digits=10)),
                ('lat', models.DecimalField(blank=True, decimal_places=10, max_digits=10)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Geo', to='webapi_app.property')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=25, null=True, verbose_name='First name')),
                ('lastName', models.CharField(blank=True, max_length=25, null=True, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_created_by', to=settings.AUTH_USER_MODEL)),
                ('property', models.ManyToManyField(to='webapi_app.Property')),
            ],
        ),
    ]
